rule Sliver_HTTP_Unobfuscated_CoreSymbols
{
	meta:
		author = "James Southcott"
		description = "Core symbols and API-like names extracted from Sliver binary"
		date = "2025-09-15"

	strings:
		$a1 = "GenerateKey"
		$a2 = "GetActiveC2"
		$a3 = "GetAssembly"
		$a4 = "GetBeaconID"
		$a5 = "GetBindPort"
		$a6 = "GetConfigID"
		$a7 = "GetFileMode"
		$a8 = "GetFilePath"
		$a9 = "GetFileType"
		$a10 = "GetFilename"
		$a11 = "GetHashFunc"
		$a12 = "GetHostname"
		$a13 = "GetInterval"
		$a14 = "GetKrb5Conf"
		$a15 = "GetMetadata"
		$a16 = "GetOriginID"
		$a17 = "GetPassword"
		$a18 = "GetPrivInfo"
		$a19 = "GetProtocol"
		$a20 = "GetProxyURL"
		$a21 = "GetRWXPages"
		$a22 = "GetRegister"
		$a23 = "GetResponse"
		$a24 = "GetRportfwd"
		$a25 = "GetSequence"
		$a26 = "GetTimezone"
		$a27 = "GetTunnelID"
		$a28 = "GetUseToken"
		$a29 = "GetUsername"
		$a30 = "GetVariable"
		$a31 = "SendRequest"
		$a32 = "SessionInit"
		$a33 = "SetAuthTime"
		$a34 = "SetChecksum"
		$a35 = "SetDeadline"
		$a36 = "SetDefaults"
		$a37 = "SetEmitFunc"
		$a38 = "SetMapIndex"
		$a39 = "SetUserName"
		$a40 = "GetAppDomain"
		$a41 = "GetArguments"
		$a42 = "GetByteValue"
		$a43 = "GetClassName"
		$a44 = "GetCloseConn"
		$a45 = "GetETypeInfo"
		$a46 = "GetEnablePTY"
		$a47 = "GetEtwBypass"
		$a48 = "GetForwarder"
		$a49 = "GetInProcess"
		$a50 = "GetIsUnicode"
		$a51 = "GetListeners"
		$a52 = "GetListening"
		$a53 = "GetLocalAddr"
		$a54 = "GetLocalPort"
		$a55 = "GetLogonType"
		$a56 = "GetProcesses"
		$a57 = "GetPublicKey"
		$a58 = "GetReadFiles"
		$a59 = "GetRecursive"
		$a60 = "GetSessionID"
		$a61 = "GetTokenUser"
		$a62 = "GetVariables"
		$a63 = "UpdateConfig"
		$a64 = "SetBasicAuth"
		$a65 = "SetGenerator"
		$a66 = "SetIterValue"
		$a67 = "SetKeepAlive"
		$a68 = "GetProcessName"
		$a69 = "GetProcessArgs"
		$a70 = "GetProfileName"
		$a71 = "GetRuntimeHost"
		$a72 = "GetServerStore"
		$a73 = "GetServiceInfo"
		$a74 = "GetServiceName"
		$a75 = "GetStringValue"
		$a76 = "GetTokenGroups"

	condition:
		uint16(0) == 0x5A4D and 30 of ($a*)
}

rule Sliver_HTTP_Unobfuscated_Runtime_IO_Extensions
{
	meta:
		author = "James Southcott"
		description = "Runtime, I/O, helper symbols and common extension token lists"
		date = "2025-09-15"

	strings:
		// low-level helpers, misc tokens, lookup/map strings, and file-ext lists
		$b1 = "HashFunc"
		$b2 = "HostPort"
		$b3 = "Hostname"
		$b4 = "InitBufs"
		$b5 = "InitJSON"
		$b6 = "Int32Ptr"
		$b7 = "Int64Ptr"
		$b8 = "IsMember"
		$b9 = "IsNormal"
		$b10 = "IsPacked"
		$b11 = "IsPseudo"
		$b12 = "IsUint64"
		$b13 = "JSONName"
		$b14 = "KexAlgos"
		$b15 = "KeyBytes"
		$b16 = "KeyUsage"
		$b17 = "Language"
		$b18 = "Linkname"
		$b19 = "Location"
		$b20 = "LookupIP"
		$b21 = "LookupMX"
		$b22 = "LookupNS"
		$b23 = "MapIndex"
		$b24 = "MapRange"
		$b25 = "MapValue"
		$b26 = "MarkDead"
		$b27 = "Messages"
		$b28 = "MulRange"
		$b29 = "Multiply"
		$b30 = "MyWindow"
		$b31 = "NameType"
		$b32 = "NewField"
		$b33 = "NewValue"
		$b34 = "NextPart"
		$b35 = "NotAfter"
		$b36 = "NumEnums"
		$b37 = "NumField"
		$b38 = "NumFiles"
		$b39 = "Password"
		$b40 = "PostForm"
		$b41 = "Protocol"
		$b42 = "ProxyURL"
		$b43 = "PushBack"
		$b44 = "LoadAcquire"
		$b45 = "LoadOrStore"
		$b46 = "LogonScript"
		$b47 = "LogonServer"
		$b48 = "LookupCNAME"
		$b49 = "LookupNetIP"
		$b50 = "SetAuthTime"
		$b51 = "SetChecksum"
		$b52 = "SetDeadline"
		$b53 = "SetEmitFunc"
		$b54 = "SetMapIndex"
		$b55 = "SetUserName"
		$b56 = "CredentialSize"
		$b57 = "DecryptEncPart"
		$b58 = "DecryptMessage"
		$b59 = "DiscardUnknown"
		$b60 = "EmailAddresses"
		$b61 = "EncodeToString"
		$b62 = "EncryptEncPart"
		$b63 = "EncryptMessage"
		$b64 = "EnumDescriptor"
		$b65 = "FindEnumByName"
		$b66 = "FindFileByPath"
		$b67 = "ForeachSetting"
		$b68 = "ForgetUnshared"
		$b69 = "GetBinaryValue"
		$b70 = "GetBindAddress"
		$b71 = "GetCoefficient"
		$b72 = "GetDescription"
		$b73 = "GetForwardPort"
		$b74 = "GetIPAddresses"
		$b75 = "GetKeyByteSize"
		$b76 = "GetLinkedToken"
		$b77 = "GetNextCheckin"
		$b78 = "EnumerateInstalledRuntimes"
		$b79 = "sshtype:"
		$b80 = "ssh:\"rest\""
		$b81 = "TGSREQGenerateAndExchange"
		$b82 = ".bat.cmd.com.css.exe.gif.htm.jpg.mjs.pdf.png.svg.xml"
		$b83 = ".avif.html.jpeg.json.wasm.webp"

	condition:
		50 of ($b*)
}

rule Sliver_HTTP_Unobfuscated_Protobuf_Fields
{
	meta:
		author = "James Southcott"
		description = "Protobuf-generated field names and related identifiers"
		date = "2025-09-15"

	strings:
		$c1 = "BinPathCprotobuf"
		$c2 = "CmdLineCprotobuf"
		$c3 = "CommandCprotobuf"
		$c4 = "EncoderCprotobuf"
		$c5 = "EntriesCprotobuf"
		$c6 = "PrivKeyCprotobuf"
		$c7 = "ProcessCprotobuf"
		$c8 = "RequestCprotobuf"
		$c9 = "RuntimeCprotobuf"
		$c10 = "ServersCprotobuf"
		$c11 = "SkStateCprotobuf"
		$c12 = "SubkeysCprotobuf"
		$c13 = "AssemblyEprotobuf"
		$c14 = "BeaconIDEprotobuf"
		$c15 = "FileModeEprotobuf"
		$c16 = "FilePathEprotobuf"
		$c17 = "HostnameEprotobuf"
		$c18 = "Krb5ConfEprotobuf"
		$c19 = "PasswordEprotobuf"
		$c20 = "PrivInfoEprotobuf"
		$c21 = "ProtocolEprotobuf"
		$c22 = "RegisterEprotobuf"
		$c23 = "ResponseEprotobuf"
		$c24 = "RportfwdEprotobuf"
		$c25 = "TimezoneEprotobuf"
		$c26 = "UsernameEprotobuf"
		$c27 = "VariableEprotobuf"
		$c28 = "ActiveC2Fprotobuf"
		$c29 = "BindPortFprotobuf"
		$c30 = "ConfigIDFprotobuf"
		$c31 = "FilenameFprotobuf"
		$c32 = "IntervalFprotobuf"
		$c33 = "OriginIDFprotobuf"
		$c34 = "ProtocolFprotobuf"
		$c35 = "ProxyURLFprotobuf"
		$c36 = "RWXPagesFprotobuf"
		$c37 = "SequenceFprotobuf"
		$c38 = "TunnelIDFprotobuf"
		$c39 = "UseTokenFprotobuf"
		$c40 = "EntryPointIprotobuf"
		$c41 = "ExecutableIprotobuf"
		$c42 = "ForwardersIprotobuf"
		$c43 = "RemoteAddrIprotobuf"
		$c44 = "SessionKeyIprotobuf"
		$c45 = "ValueNamesIprotobuf"
		$c46 = "AmsiBypassJprotobuf"
		$c47 = "HideWindowJprotobuf"
		$c48 = "AmsiBypassKprotobuf"
		$c49 = "BindAddressKprotobuf"
		$c50 = "DescriptionKprotobuf"
		$c51 = "IPAddressesKprotobuf"
		$c52 = "ProcessNameKprotobuf"
		$c53 = "ProfileNameKprotobuf"
		$c54 = "ServiceInfoKprotobuf"
		$c55 = "ServiceNameKprotobuf"
		$c56 = "StringValueKprotobuf"
		$c57 = "ForwardPortLprotobuf"
		$c58 = "NextCheckinLprotobuf"
		$c59 = "ProcessArgsLprotobuf"
		$c60 = "ServerStoreLprotobuf"
		$c61 = "ArchitectureMprotobuf"
		$c62 = "BeaconJitterNprotobuf"
		$c63 = "PollIntervalNprotobuf"
		$c64 = "NetInterfacesOprotobuf"
		$c65 = "RemoteAddressOprotobuf"
		$c66 = "CreateReversePprotobuf"
		$c67 = "PeerFailureAtPprotobuf"
		$c68 = "UsedForAccessPprotobuf"
		$c69 = "ForwardAddressQprotobuf"
		$c70 = "HostingProcessQprotobuf"
		$c71 = "PivotSessionIDQprotobuf"
		$c72 = "BeaconIntervalRprotobuf"
		$c73 = "SignedUserCertRprotobuf"
		$c74 = "TimezoneOffsetRprotobuf"
		$c75 = "UnreadableFilesUprotobuf"
		$c76 = "ProcessIntegrityUprotobuf"
		$c77 = "EnabledByDefaultVprotobuf"
		$c78 = "ReconnectIntervalXprotobuf"
		$c79 = "ReconnectIntervalYprotobuf"
		$c80 = "PublicKeySignatureYprotobuf"
		$c81 = "ServiceDescriptionYprotobuf"

	condition:
		40 of ($c*)
}
